pd-finalpj/auctionTTang-BE

src/main/java/com/encore/auction/controller/manager/requests/ManagerSginUpRequest.java
src/main/java/com/encore/auction/controller/manager/responses/ManagerDetailsResponse.java
src/main/java/com/encore/auction/controller/user/api/UserController.java
src/main/java/com/encore/auction/controller/user/requests/UserLoginRequest.java
src/main/java/com/encore/auction/controller/user/requests/UserSiginUpRequest.java
src/main/java/com/encore/auction/controller/user/responses/UserDetailsResponse.java
src/main/java/com/encore/auction/controller/user/responses/UserIdResponse.java
src/main/java/com/encore/auction/service/user/UserService.java
src/test/java/com/encore/auction/controller/user/api/UserControllerTest.java

#4 Create User Controller and Test case

---

build.gradle
src/main/java/com/encore/auction/controller/user/api/UserController.java
src/main/java/com/encore/auction/controller/user/requests/UserDeleteRequest.java
src/main/java/com/encore/auction/controller/user/requests/UserUpdateRequest.java
src/main/java/com/encore/auction/controller/user/responses/UserDeleteResponse.java
src/main/java/com/encore/auction/controller/user/responses/UserDetailsResponse.java
src/main/java/com/encore/auction/service/user/UserService.java
src/main/resources/static/docs/open-api-3.0.1.json
src/test/java/com/encore/auction/controller/user/api/UserControllerTest.java

#3 Create User Controller and Test Case

---

src/main/java/com/encore/auction/controller/bookmark/api/BookmarkListController.java
src/main/java/com/encore/auction/controller/bookmark/responses/BookmarkDetailsListResponse.java
src/main/java/com/encore/auction/controller/bookmark/responses/BookmarkDetailsResponse.java
src/main/java/com/encore/auction/service/bookmark/BookmarkListService.java
src/test/java/com/encore/auction/controller/bookmark/api/BookmarkListControllerTest.java

#11 
북마크된 acution 리스트 조회 컨트롤러 및 테스트 케이스

#11 Create Bookmark List Controller and Test Case

---

.idea/compiler.xml
.idea/misc.xml
build.gradle
src/main/java/com/encore/auction/controller/bookmark/responses/BookmarkDetailsResponse.java
src/main/java/com/encore/auction/exception/WrongTimeException.java
src/main/java/com/encore/auction/repository/BookmarkListRetrieveRepository.java
src/main/java/com/encore/auction/repository/QuerydslBookmarkListRetrieveRepository.java
src/main/java/com/encore/auction/service/bookmark/BookmarkListService.java
src/main/java/com/encore/auction/utils/validator/LocalDateTimeValidator.java
src/test/java/com/encore/auction/controller/bookmark/api/BookmarkListControllerTest.java

#16 
유저 아이디로 북마크 리스트 조회 service 로직 및 querydsl 작성 완료

#16 Create Find Bookmark List By User Id service

---

src/main/java/com/encore/auction/controller/bidding/bidding/api/BiddingListController.java
src/main/java/com/encore/auction/controller/bidding/bidding/responses/BiddingDetailsListResponse.java
src/main/java/com/encore/auction/controller/bidding/bidding/responses/BiddingDetailsResponse.java
src/main/java/com/encore/auction/service/bidding/bidding/BiddingListService.java
src/test/java/com/encore/auction/controller/bidding/bidding/api/BiddingListControllerTest.java
src/test/java/com/encore/auction/controller/bookmark/api/BookmarkListControllerTest.java

#18 
유저 마이페이지
유저 아이디로 입찰 내역 목록 불러오기 컨트롤러 및 테스트 케이스 완성

#18 Create Bidding List Controller and Test case

---

src/main/java/com/encore/auction/repository/BiddingListRetrieveRepository.java
src/main/java/com/encore/auction/repository/QuerydslBiddingListRetrieveRepository.java
src/main/java/com/encore/auction/service/bidding/bidding/BiddingListService.java

#20 
유저 입찰 목록 가져오기 querydsl 및 서비스 로직 완료

#20 Create Bidding List Service

---

src/main/java/com/encore/auction/controller/bidding/aftbidding/api/AftBiddingListController.java
src/main/java/com/encore/auction/controller/bidding/aftbidding/responses/AftBiddingDetailsListResponse.java
src/main/java/com/encore/auction/controller/bidding/aftbidding/responses/AftBiddingDetailsResponse.java
src/main/java/com/encore/auction/service/bidding/aftbidding/AftBiddingListService.java
src/test/java/com/encore/auction/controller/bidding/aftbidding/api/AftBiddingListControllerTest.java
src/test/java/com/encore/auction/controller/bidding/bidding/api/BiddingListControllerTest.java

#22 Create Aft Bidding controller and Test case

---

src/main/java/com/encore/auction/controller/bidding/bidding/api/BiddingController.java
src/main/java/com/encore/auction/controller/bidding/bidding/requests/BiddingRegisterRequest.java
src/main/java/com/encore/auction/controller/bidding/bidding/requests/BiddingUpdateRequest.java
src/main/java/com/encore/auction/controller/bidding/bidding/responses/BiddingDeleteResponse.java
src/main/java/com/encore/auction/controller/bidding/bidding/responses/BiddingIdResponse.java
src/main/java/com/encore/auction/controller/bidding/bidding/responses/BiddingRetrieveResponse.java
src/main/java/com/encore/auction/controller/user/requests/UserDeleteRequest.java
src/main/java/com/encore/auction/model/bidding/aftbidding/BiddingResult.java
src/main/java/com/encore/auction/service/bidding/bidding/BiddingService.java
src/test/java/com/encore/auction/controller/bidding/bidding/api/BiddingControllerTest.java

#27 Create Bidding CRUD Controller and Test case

---

src/main/java/com/encore/auction/model/bidding/bidding/Bidding.java
src/main/java/com/encore/auction/repository/AuctionItemRepository.java
src/main/java/com/encore/auction/repository/BiddingRepository.java
src/main/java/com/encore/auction/repository/BiddingRetrieveRepository.java
src/main/java/com/encore/auction/repository/QuerydslBiddingListRetrieveRepository.java
src/main/java/com/encore/auction/repository/QuerydslBiddingRetrieveRepository.java
src/main/java/com/encore/auction/repository/QuerydslBookmarkListRetrieveRepository.java
src/main/java/com/encore/auction/service/bidding/bidding/BiddingService.java
src/main/java/com/encore/auction/utils/mapper/BiddingMapper.java
src/main/java/com/encore/auction/utils/validator/LocalDateTimeValidator.java

#30 Create Bidding Service

---

.idea/codeStyles/codeStyleConfig.xml
.idea/modules.xml
.idea/modules/auction.main.iml
src/main/java/com/encore/auction/controller/manager/api/ManagerController.java
src/main/java/com/encore/auction/controller/manager/requests/ManagerLoginRequest.java
src/main/java/com/encore/auction/controller/manager/requests/ManagerUpdateRequest.java
src/main/java/com/encore/auction/controller/manager/responses/ManagerDeleteResponse.java
src/main/java/com/encore/auction/controller/manager/responses/ManagerDetailsResponse.java
src/main/java/com/encore/auction/controller/manager/responses/ManagerIdResponse.java
src/main/java/com/encore/auction/model/manager/Manager.java
src/main/java/com/encore/auction/repository/ManagerRepository.java
src/main/java/com/encore/auction/service/manager/ManagerService.java
src/main/java/com/encore/auction/service/user/UserService.java
src/main/java/com/encore/auction/utils/mapper/ManagerMapper.java
src/test/java/com/encore/auction/controller/manager/api/ManagerControllerTest.java

#13 Create Manager Controller and Test Case

---

src/main/java/com/encore/auction/controller/bookmark/api/BookmarkController.java
src/main/java/com/encore/auction/controller/bookmark/requests/BookmarkRegisterRequest.java
src/main/java/com/encore/auction/controller/bookmark/responses/BookmarkDeleteResponse.java
src/main/java/com/encore/auction/controller/bookmark/responses/BookmarkRegisterResponse.java
src/main/java/com/encore/auction/service/bookmark/BookmarkListService.java
src/main/java/com/encore/auction/service/bookmark/BookmarkService.java
src/test/java/com/encore/auction/controller/bookmark/api/BookmarkControllerTest.java
src/test/java/com/encore/auction/controller/bookmark/api/BookmarkListControllerTest.java

#32 Create Bookmark Controller and Test Case

---

src/main/java/com/encore/auction/model/bookmark/Bookmark.java
src/main/java/com/encore/auction/repository/BookmarkRepository.java
src/main/java/com/encore/auction/service/bookmark/BookmarkService.java
src/main/java/com/encore/auction/utils/mapper/BookmarkMapper.java

#34 Create Bookmark Service

---

src/main/java/com/encore/auction/model/comment/Comment.java
src/main/java/com/encore/auction/repository/CommentRepository.java
src/main/java/com/encore/auction/service/comment/CommentService.java
src/main/java/com/encore/auction/utils/mapper/CommentMapper.java

#39 Create Comment Service

---

.idea/compiler.xml
src/main/java/com/encore/auction/controller/manager/api/ManagerController.java
src/main/java/com/encore/auction/controller/manager/requests/ManagerDeleteRequest.java
src/main/java/com/encore/auction/controller/manager/requests/ManagerSginUpRequest.java
src/main/java/com/encore/auction/controller/manager/requests/ManagerSignUpRequest.java
src/main/java/com/encore/auction/controller/manager/requests/ManagerUpdateRequest.java
src/main/java/com/encore/auction/controller/manager/responses/ManagerDetailsResponse.java
src/main/java/com/encore/auction/controller/manager/responses/ManagerIdCheckResponse.java
src/main/java/com/encore/auction/controller/user/api/UserController.java
src/main/java/com/encore/auction/controller/user/requests/UserSignUpRequest.java
src/main/java/com/encore/auction/controller/user/responses/UserIdCheckResponse.java
src/main/java/com/encore/auction/model/manager/Manager.java
src/main/java/com/encore/auction/service/manager/ManagerService.java
src/main/java/com/encore/auction/service/user/UserService.java
src/main/java/com/encore/auction/utils/mapper/ManagerMapper.java
src/main/java/com/encore/auction/utils/mapper/UserMapper.java
src/test/java/com/encore/auction/controller/manager/api/ManagerControllerTest.java
src/test/java/com/encore/auction/controller/user/api/UserControllerTest.java

#41 
매니저 CRUD 서비스 구현 및 유저 보안, 유저 매니저 아이디 중복 체크 로직 구현

#41 Create Manager Service

---

src/main/java/com/encore/auction/model/notice/Notice.java
src/main/java/com/encore/auction/repository/NoticeRepository.java
src/main/java/com/encore/auction/service/notice/NoticeService.java
src/main/java/com/encore/auction/utils/mapper/CommentMapper.java
src/main/java/com/encore/auction/utils/mapper/NoticeMapper.java

#45 Create Notice Service

---

src/main/java/com/encore/auction/controller/auction/api/AuctionController.java
src/main/java/com/encore/auction/controller/auction/responses/AuctionRetrieveResponse.java
src/main/java/com/encore/auction/model/auction/item/AuctionItem.java
src/main/java/com/encore/auction/repository/CommentRepository.java
src/main/java/com/encore/auction/repository/QuerydslBiddingListRetrieveRepository.java
src/main/java/com/encore/auction/service/auction/AuctionService.java
src/main/java/com/encore/auction/utils/mapper/AuctionMapper.java
src/test/java/com/encore/auction/controller/auction/api/AuctionControllerTest.java

#47 
옥션 아이템 CRUD Service 로직 구현 완료

#47 Create Auction Item Service

---

src/main/java/com/encore/auction/exception/GlobalExceptionHandler.java
src/main/java/com/encore/auction/exception/response/ExceptionResponse.java

#49 Create Exception Handler

---

.idea/codeStyles/codeStyleConfig.xml
.idea/compiler.xml
build.gradle
src/main/java/com/encore/auction/controller/filtering/api/FilteringController.java
src/main/java/com/encore/auction/controller/filtering/responses/FilteringItemsListResponse.java
src/main/java/com/encore/auction/controller/filtering/responses/FilteringItemsResponse.java
src/main/java/com/encore/auction/repository/FilteringAuctionItemListRepository.java
src/main/java/com/encore/auction/repository/FilteringRepository.java
src/main/java/com/encore/auction/repository/QuerydslFilteringAuctionItemListRepository.java
src/main/java/com/encore/auction/service/filtering/FilteringService.java
src/main/java/com/encore/auction/utils/mapper/FilteringMapper.java
src/test/java/com/encore/auction/controller/filtering/api/FilteringControllerTest.java

매물 조건별 필터링 컨트롤러, 서비스, 레퍼지토리 및 테스트 케이스 구현

#14 Create Filtering Controller and Test Case

---

src/main/java/com/encore/auction/service/user/UserService.java
src/test/java/com/encore/auction/controller/user/api/UserControllerIntegrationTest.java
src/test/java/com/encore/auction/controller/user/api/UserControllerTest.java

#55 Create User Integration Controller Test

---

.idea/encodings.xml
src/test/java/com/encore/auction/controller/manager/api/ManagerControllerIntegration.java
src/test/java/com/encore/auction/controller/user/api/UserControllerIntegrationTest.java

#57 
manager Controller 통합 테스트 완료 했습니다.

#57 Create manager Controller Integration Test

---

src/main/java/com/encore/auction/controller/filtering/api/FilteringController.java
src/main/java/com/encore/auction/controller/filtering/responses/FilteringItemsResponse.java
src/main/java/com/encore/auction/repository/QuerydslFilteringAuctionItemListRepository.java
src/main/java/com/encore/auction/service/filtering/FilteringService.java
src/test/java/com/encore/auction/controller/filtering/api/FilteringControllerIntegrationTest.java
src/test/java/com/encore/auction/controller/filtering/api/FilteringControllerTest.java

#59 지역, 날짜, 매물 종류, 유찰 횟수를 기반으로 매물 조회 API 구현

#59 Create Filtering AuctionItem Controller Integration Test

---

src/main/java/com/encore/auction/controller/auction/requests/AuctionUpdateRequest.java
src/main/java/com/encore/auction/controller/filtering/responses/FilteringItemsResponse.java
src/main/java/com/encore/auction/model/auction/item/AuctionItem.java
src/main/java/com/encore/auction/service/auction/AuctionService.java
src/main/java/com/encore/auction/utils/mapper/AuctionMapper.java
src/test/java/com/encore/auction/controller/auction/api/AuctionControllerIntegrationTest.java
src/test/java/com/encore/auction/controller/auction/api/AuctionControllerTest.java

#61 Create Auction item Integration Controller test

---

src/main/java/com/encore/auction/controller/auction/requests/AuctionCreateRequest.java
src/main/java/com/encore/auction/controller/auction/requests/AuctionUpdateRequest.java
src/main/java/com/encore/auction/controller/bidding/bidding/requests/BiddingRegisterRequest.java
src/main/java/com/encore/auction/controller/bidding/bidding/requests/BiddingUpdateRequest.java
src/main/java/com/encore/auction/controller/bookmark/requests/BookmarkRegisterRequest.java
src/main/java/com/encore/auction/controller/comment/requests/CommentRegisterRequest.java
src/main/java/com/encore/auction/controller/comment/requests/CommentUpdateRequest.java
src/main/java/com/encore/auction/controller/manager/requests/ManagerDeleteRequest.java
src/main/java/com/encore/auction/controller/manager/requests/ManagerLoginRequest.java
src/main/java/com/encore/auction/controller/manager/requests/ManagerSignUpRequest.java
src/main/java/com/encore/auction/controller/manager/requests/ManagerUpdateRequest.java
src/main/java/com/encore/auction/controller/notice/requests/NoticeRegisterRequest.java
src/main/java/com/encore/auction/controller/notice/requests/NoticeUpdateRequest.java
src/main/java/com/encore/auction/controller/user/requests/UserDeleteRequest.java
src/main/java/com/encore/auction/controller/user/requests/UserLoginRequest.java
src/main/java/com/encore/auction/controller/user/requests/UserSignUpRequest.java
src/main/java/com/encore/auction/controller/user/requests/UserUpdateRequest.java

유효성 검사에서 에러 발생 시 출력할 에러 메세지 생성

#65 Create Validation Error Message

---

src/main/java/com/encore/auction/controller/imagefile/api/ImageFileController.java
src/main/java/com/encore/auction/controller/imagefile/requests/ImageFileCreateRequest.java
src/main/java/com/encore/auction/controller/imagefile/requests/ImageFileDeleteRequest.java
src/main/java/com/encore/auction/controller/imagefile/responses/ImageFileCreateResponse.java
src/main/java/com/encore/auction/controller/imagefile/responses/ImageFileDeleteResponse.java
src/main/java/com/encore/auction/model/imagefile/ImageFile.java
src/main/java/com/encore/auction/repository/ImageFileRepository.java
src/main/java/com/encore/auction/service/imagefile/ImageFileService.java

#69 Create Image File Upload Basic Structure

---

src/main/java/com/encore/auction/controller/imagefile/api/ImageFileController.java
src/main/java/com/encore/auction/controller/imagefile/requests/ImageFileCreateRequest.java
src/main/java/com/encore/auction/controller/imagefile/requests/ImageFileDeleteRequest.java
src/main/java/com/encore/auction/controller/imagefile/responses/ImageFileCreateResponse.java
src/main/java/com/encore/auction/controller/imagefile/responses/ImageFileDeleteResponse.java
src/main/java/com/encore/auction/model/imagefile/ImageFile.java
src/main/java/com/encore/auction/service/imagefile/ImageFileService.java

#71 Create ImageFileController

---

.idea/compiler.xml
build.gradle
src/main/java/com/encore/auction/config/RedisConfig.java
src/main/java/com/encore/auction/controller/auction/api/AuctionController.java
src/main/java/com/encore/auction/controller/filtering/api/FilteringController.java
src/main/java/com/encore/auction/controller/filtering/requests/FilteringAuctionItemRequest.java
src/main/java/com/encore/auction/controller/filtering/requests/SortCategory.java
src/main/java/com/encore/auction/controller/filtering/responses/FilteringItemsListResponse.java
src/main/java/com/encore/auction/controller/filtering/responses/FilteringItemsResponse.java
src/main/java/com/encore/auction/controller/notice/api/NoticeController.java
src/main/java/com/encore/auction/controller/notice/requests/NoticeRetrieveRequest.java
src/main/java/com/encore/auction/controller/notice/responses/NoticeDetailsListResponse.java
src/main/java/com/encore/auction/controller/notice/responses/NoticeDetailsResponse.java
src/main/java/com/encore/auction/exception/GlobalExceptionHandler.java
src/main/java/com/encore/auction/model/filtering/Filtering.java
src/main/java/com/encore/auction/repository/FilteringAuctionItemListRepository.java
src/main/java/com/encore/auction/repository/FilteringRedisRepository.java
src/main/java/com/encore/auction/repository/NoticeRepository.java
src/main/java/com/encore/auction/repository/QuerydslFilteringAuctionItemListRepository.java
src/main/java/com/encore/auction/service/filtering/FilteringService.java
src/main/java/com/encore/auction/service/notice/NoticeService.java
src/main/java/com/encore/auction/utils/mapper/FilteringMapper.java
src/main/java/com/encore/auction/utils/mapper/NoticeMapper.java
src/main/resources/application.yml

#75 
#78 
필터링 캐쉬 처리 완료 및 필터링 보완

#75 Redis 캐시 처리 #78 Redis 연동

---

src/main/java/com/encore/auction/config/WebConfig.java
src/main/java/com/encore/auction/controller/address/api/AddressController.java
src/main/java/com/encore/auction/controller/address/responses/AddressDetailsListResponse.java
src/main/java/com/encore/auction/controller/address/responses/AddressDetailsResponse.java
src/main/java/com/encore/auction/controller/filtering/requests/FilteringAuctionItemRequest.java
src/main/java/com/encore/auction/repository/filtering/QuerydslFilteringAuctionItemListRepository.java
src/main/java/com/encore/auction/service/address/AddressService.java
src/main/java/com/encore/auction/service/filtering/FilteringService.java
src/main/java/com/encore/auction/service/imagefile/ImageFileService.java

#87 필터링 주소 api

---

src/main/java/com/encore/auction/controller/auction/api/AuctionController.java
src/main/java/com/encore/auction/controller/auction/responses/AuctionRetrieveResponse.java
src/main/java/com/encore/auction/controller/imagefile/api/ImageFileController.java
src/main/java/com/encore/auction/controller/imagefile/responses/ImageFileUrlResponse.java
src/main/java/com/encore/auction/controller/manager/requests/ManagerSignUpRequest.java
src/main/java/com/encore/auction/controller/manager/requests/ManagerUpdateRequest.java
src/main/java/com/encore/auction/exception/GlobalExceptionHandler.java
src/main/java/com/encore/auction/model/filtering/Filtering.java
src/main/java/com/encore/auction/model/manager/Manager.java
src/main/java/com/encore/auction/repository/ImageFileRepository.java
src/main/java/com/encore/auction/service/auction/AuctionService.java
src/main/java/com/encore/auction/service/bidding/aftbidding/AftBiddingListService.java
src/main/java/com/encore/auction/service/bidding/bidding/BiddingListService.java
src/main/java/com/encore/auction/service/bidding/bidding/BiddingService.java
src/main/java/com/encore/auction/service/bookmark/BookmarkListService.java
src/main/java/com/encore/auction/service/bookmark/BookmarkService.java
src/main/java/com/encore/auction/service/comment/CommentService.java
src/main/java/com/encore/auction/service/imagefile/ImageFileService.java
src/main/java/com/encore/auction/service/manager/ManagerService.java
src/main/java/com/encore/auction/service/notice/NoticeService.java
src/main/java/com/encore/auction/service/user/UserService.java
src/main/java/com/encore/auction/utils/mapper/AuctionMapper.java
src/main/java/com/encore/auction/utils/mapper/ImageFileMapper.java
src/main/java/com/encore/auction/utils/mapper/ManagerMapper.java
src/main/java/com/encore/auction/utils/token/JwtProvider.java

#92 
사진 로드 및 auction regist 사진 업로드 포함
manager entity 수정

#92 Auction item detail response 수정

---

src/main/java/com/encore/auction/controller/auction/api/AuctionFailedLogController.java
src/main/java/com/encore/auction/controller/auction/responses/AuctionFailedLogDetailsResponse.java
src/main/java/com/encore/auction/controller/auction/responses/AuctionFailedLogListResponse.java
src/main/java/com/encore/auction/repository/auction/AuctionFailedLogRepository.java
src/main/java/com/encore/auction/service/auction/AuctionFailedLogService.java
src/main/java/com/encore/auction/utils/mapper/AuctionFailedLogMapper.java

#96 Auction Failed Log List 추가
